version: '3.5'
services:
  nginx:
    container_name: nginx_elk
    image: nginx:1.21.5-perl
    tty: true
    volumes:
      - .:/var/www/html
      - ./docker/dependencies/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/CA:/certs
    ports:
      - "8080:8443"
    dns:
      - 10.100.101.50
      - 10.100.101.51
      - 1.1.1.1
    networks:
      - docker_net
  php:
    build: ./docker/dependencies/php
    container_name: php_elk
    tty: true
    volumes:
      - .:/var/www/html
    networks:
      - docker_net
networks:
  docker_net:
    external:
      name: docker_net
