version: '3.8'
services:
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    tty: true
    volumes:
      - .:/var/www/html
      - ./docker/dependencies/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/CA:/certs
    ports:
      - "9090:8443"
    networks:
      - red-network
  php:
    image: php:8.2.14-fpm
    tty: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .:/var/www/html
    networks:
      - red-network
networks:
  red-network:
    driver: overlay